/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar/day` | `/calendar/day`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/logout` | `/profile/logout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/settings` | `/profile/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/login` | `/profile/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registry` | `/registry`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registry/grades` | `/registry/grades`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registry/exams` | `/registry/exams`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calendar/day` | `/calendar/day`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/logout` | `/profile/logout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/settings` | `/profile/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/login` | `/profile/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/registry` | `/registry`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/registry/grades` | `/registry/grades`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/registry/exams` | `/registry/exams`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calendar/day${`?${string}` | `#${string}` | ''}` | `/calendar/day${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/logout${`?${string}` | `#${string}` | ''}` | `/profile/logout${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/settings${`?${string}` | `#${string}` | ''}` | `/profile/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/login${`?${string}` | `#${string}` | ''}` | `/profile/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/registry${`?${string}` | `#${string}` | ''}` | `/registry${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/registry/grades${`?${string}` | `#${string}` | ''}` | `/registry/grades${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/registry/exams${`?${string}` | `#${string}` | ''}` | `/registry/exams${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar/day` | `/calendar/day`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/logout` | `/profile/logout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/settings` | `/profile/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/login` | `/profile/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registry` | `/registry`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registry/grades` | `/registry/grades`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registry/exams` | `/registry/exams`; params?: Router.UnknownInputParams; };
    }
  }
}
